config/routes.rb
Rails.application.routes.draw do


  resources :users, :trips, :locations, :countries, :visits, :steps

  get "/login" => 'session#new', :as => 'login'
  post "/login" => 'session#create'
  delete "/logout" => 'session#destroy', :as => 'logout'

end

app/models/visit.rb
# == Schema Information
#
# Table name: visits
#
#  id             :integer          not null, primary key
#  name           :text
#  country_id     :integer
#  theme_id       :integer
#  description    :text
#  image          :text
#  visitLatitude  :text
#  visitLongitude :text
#

class Visit < ActiveRecord::Base
  belongs_to :country
  belongs_to :theme
  has_many :steps
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

    def index
      @visits = Visit.all
      @countries = Country.all
      @locations = Location.all

    end

    def show
      @visit = Visit.find params[:id]
    end

    def new
      if @current_user && @current_user.admin
      @visit = Visit.new
      end
    end

    def create
      if @current_user && @current_user.admin
      visit = Visit.create visit_params

      redirect_to visit
      end
    end

    def edit
      if @current_user && @current_user.admin
      @visit = Visit.find params[:id]
      end
    end

    def update
      if @current_user && @current_user.admin
      visit = Visit.find params[:id]
      visit.update visit_params

      redirect_to visit
      end
    end

    def destroy
      if @current_user && @current_user.admin
      visit = Visit.find params[:id]
      visit.destroy

      redirect_to visits_path
      end
    end

    private

    def visit_params
      params.require(:visit).permit(:name, :country_id, :theme_id, :description, :image, :visitLatitude, :visitLongitude)
    end

end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<!-- t.text    "name"
t.integer "country_id"
t.integer "theme_id"
t.text    "description"
t.text    "image"
t.text    "visitLatitude"
t.text    "visitLongitude" -->


<%= form_for @visit do |f| %>

<div class='col-md-6 col-md-offset-3'>
  <div class="stepsDetailsShow specialForm">

  <p>
    <%= f.label :name, :class => "labels", :class => "label1" %>
    <%= f.text_field :name, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :country_id, :class => "labels", :class => "label1" %>
      <% sorted_countries = Country.all.sort_by { |c| c.name } %>
    <%= f.select :country_id, sorted_countries.map { |a| [ a.name, a.id ]}, :include_blank => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :theme_id, :class => "labels", :class => "label1" %>
        <% sorted_themes = Theme.all.sort_by { |t| t.name } %>
    <%= f.select :theme_id, sorted_themes.map { |a| [ a.name, a.id ]}, :include_blank => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :description, :class => "labels", :class => "label1" %>
    <%= f.text_field :description, :required => true, :class => "inputs", :class => "label2" %>
  </p>



  <p>
    <%= f.label :image, :class => "labels", :class => "label1" %>
    <%= f.url_field :image, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :visitLatitude, :class => "labels", :class => "label1" %>
    <%= f.text_field :visitLatitude, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :visitLongitude, :class => "labels", :class => "label1" %>
    <%= f.text_field :visitLongitude, :required => true, :class => "inputs", :class => "label2" %>
  </p>


<br>

  <%= f.submit %>

</div>
</div>

<% end %>

app/views/visits/edit.html.erb
<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
        <h2>Edit</h2>
      </div>
  </div>
  <br>

<% if @current_user %>
    <%= render :partial => 'form' %>
<% end %>

</div>

app/views/visits/index.html.erb
<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
                <h2>This should show all the visits:</h2>
          </div>
  </div>

<% if @current_user && @current_user.admin %>

    <br>

      <div class='row text-center'>
              <div class='col-md-12'>
                    <button type='button' class='btn btn-lg btn-default'><%= link_to "Create a new visit", new_visit_path %></button>
              </div>
      </div>

  <br>
<% end %>




  <% sorted_locations = @locations.sort {|l1, l2| l1.name <=> l2.name } %>
  <% sorted_locations.each do |location| %>

        <% sorted_countries = location.countries.sort {|c1, c2| c1.name <=> c2.name } %>
        <% sorted_countries.each do |country| %>

              <% sorted_visits = country.visits.sort {|v1, v2| v1.name <=> v2.name } %>
              <% sorted_visits.each do |visit| %>

                    <div class='col-md-4'>
                      <div class="stepsDetailsShow">

                          <h4><%= link_to visit.name, "/visits/#{visit.id}" %></h4>

                          <%= link_to(image_tag( visit.image, :class => 'thumbnail'), visit) %>

                          <% if visit.country %>
                            <h5>Location: <span><%= link_to visit.country.location.name, "/locations/#{visit.country.location.id}" %></span></h5>
                            <h5>Country: <span><%= link_to visit.country.name, "/countries/#{visit.country.id}" %></span></h5>
                          <% end %>

                          <h5>Description: <span><%= truncate( visit.description, :length => 300)%></span></h5>
                          <h5>Visit_id: <%= visit.id %></h5>
                        </div>
                </div>
          <% end %>
      <% end %>
  <% end %>

</div>

app/views/visits/new.html.erb
<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
        <h2>Create a new visit:</h2>
      </div>
  </div>

  <br>

<% if @current_user %>
      <%= render :partial => 'form' %>
<% end %>

</div>

app/views/visits/show.html.erb
<br>
<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
                <h2><%= @visit.name %></h2>
          </div>
  </div>

  <br>

<div class='row'>
        <div class='col-md-12'>
                <div id="map"></div>
        </div>
</div>

<br>
<div class='row'>
    <div class='col-md-8'>
            <div class="stepsDetailsShow">
                  <%= link_to(image_tag( @visit.image, :class => 'featured'), @visit) %>
            </div>
    </div>
    <div class='col-md-4'>
      <div class="stepsDetailsShow">
          <h5>Location: <span><%= link_to @visit.country.location.name, "/locations/#{@visit.country.location.id}" %></span></h5>
          <h5>Country: <span><%= link_to @visit.country.name, "/countries/#{@visit.country.id}" %></span></h5>
          <h5>Description: <span><%= @visit.description %></span></h5>

          <br>

<% if @current_user && @current_user.admin %>
        <div class='row text-center'>
        <button type='button' class='btn btn btn-default'><%= link_to "Edit Visit", edit_visit_path( @visit ), :class => "links" %></button>

        <button type='button' class='btn btn btn-default'><%= link_to "Delete Visit", @visit, :method => :delete, :data => { :confirm => 'Are you sure?'}, :class => "links" %></button>
        </div>
<% end %>

      </div>
    </div>
  </div>
  </div>



<script>
    function initMap() {

      var mapDiv = document.getElementById('map');
      var map = new google.maps.Map(mapDiv, {
        center: {lat: <%= @visit.visitLatitude %>, lng: <%= @visit.visitLongitude %>},
        zoom: 6
      });

      var iconBase = 'http://maps.google.com/mapfiles/kml/paddle/A.png';

      var marker = new google.maps.Marker({
        position: {lat: <%= @visit.visitLatitude %>, lng: <%= @visit.visitLongitude %>},
        map: map,
        icon: iconBase
      });
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
      async defer></script>