config/routes.rb
Rails.application.routes.draw do


  resources :users, :trips, :locations, :countries, :visits, :steps

  get "/login" => 'session#new', :as => 'login'
  post "/login" => 'session#create'
  delete "/logout" => 'session#destroy', :as => 'logout'

end

app/models/user.rb
# login $ rails generate model User name:text email:text password_digest:text

# add gems:
      # gem 'annotate'
      # gem 'pry-rails'
      # login $ bundle
      # login $ annotate
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :text
#  email           :text
#  password_digest :text
#  admin           :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :trips
  has_many :steps, :through => :trips
end

app/controllers/users_controller.rb
# login $ rails generate controller Users index new show edit


class UsersController < ApplicationController


  def index
     @users = User.all
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  def edit
      @user = User.find params[:id]
  end

  def update
      user = User.find params[:id]
      user.update user_params

      redirect_to user

  end


    def destroy
        user = User.find params[:id]
        user.destroy

        redirect_to users_path

    end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<div class='col-md-6 col-md-offset-3'>
  <div class="stepsDetailsShow specialForm">

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>


  <p>
      <%= f.label :email, :class => "label1" %>
      <%= f.email_field :email, :required => true, :class => "label2" %>
  </p>
  <p>
      <%= f.label :name, :class => "label1"  %>
      <%= f.text_field :name, :required => true, :class => "label2" %>
  </p>

  <p>
    <%= f.label :image, :class => "label1" %>
    <%= f.url_field :image, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
      <%= f.label :password, :class => "label1"  %>
      <%= f.password_field :password, :required => true, :class => "label2" %>
  </p>
  <p>
      <%= f.label :password_confirmation, :class => "label1"  %>
      <%= f.password_field :password_confirmation, :required => true, :class => "label2" %>
  </p>
<br>
  <%= f.submit "Create/Edit account" %>
</div>
</div>

<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
      <h2>Edit profile</h2>
    </div>
</div>

<br>

<%= render :partial => 'form' %>

</div>

app/views/users/index.html.erb
<% if @current_user && @current_user.admin %>

<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
                <h2>All the users:</h2>
              </div>
          </div>


      <% @users.each do |user| %>
      <div class='col-md-4'>
        <div class="stepsDetailsShow specialForm">

            <h5>Username: <span><%= link_to( user.name, user_path(user) ) %></span></h5>
            <h5>Email: <span><%= user.email %></span></h5>
            <h5>User admin status: <span><%= user.admin %></span></h5>
            <%= link_to(image_tag( user.image, :class => 'thumbnail'), user) %>

        </div>
      </div>


      <% end %>

      <% else %>

        <div class='row text-center'>
                <div class='col-md-12'>
            <h3>Hello, how are you today?</h3>
            <h4>Select the links above to login or to create an account.</h4>
          </div>
        </div>

      </div>
<% end %>

app/views/users/new.html.erb
<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
                    <h2>Sign up</h2>
          </div>
  </div>

<br>

<%= render :partial => 'form' %>

</div>

app/views/users/show.html.erb
<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
                <h2><%= @user.name %></h2>
              </div>
          </div>


      <div class='col-md-4 col-md-offset-4'>
        <div class="stepsDetailsShow specialForm">
                <h4><%= @user.email %></h4>
                <h5>User admin status: <span><%= @user.admin %></span></h5>
                <!-- <p> Password digest: <%= @user.password_digest %> </p> -->

                <%= link_to(image_tag( @user.image, :class => 'thumbnail'), @user) %>

                <br>
                <div class='row text-center'>
                <button type='button' class='btn btn-lg btn-default'><%= link_to( "Check your trips", trips_path( @user)) %></button>
                </div>


                <br>
                <br>

                <div class='row text-center'>
                    <button type='button' class='btn btn btn-default'><%= link_to( "Edit user", edit_user_path( @user)) %></button>
                    <button type='button' class='btn btn btn-default'><%= link_to( "Delete user", user_path( @user), :method => :delete, :data => { :confirm => 'Are you sure?'}) %></button>
                </div>
        </div>
        </div>

  </div>