config/routes.rb
Rails.application.routes.draw do


  resources :users, :trips, :locations, :countries, :visits, :steps

  get "/login" => 'session#new', :as => 'login'
  post "/login" => 'session#create'
  delete "/logout" => 'session#destroy', :as => 'logout'

end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id               :integer          not null, primary key
#  name             :text
#  location_id      :integer
#  capitalCity      :text
#  currency         :text
#  population       :text
#  area             :text
#  popDensity       :text
#  flag             :text
#  visa             :text
#  capitalLatitude  :text
#  capitalLongitude :text
#  language         :text
#

class Country < ActiveRecord::Base
  belongs_to :location
  has_many :visits
  has_many :steps, :through => :visits
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController


  def index
    @countries = Country.all
    @locations = Location.all

  end

  def show
    @country = Country.find params[:id]
  end


  def new
    if @current_user && @current_user.admin
    @country = Country.new
    end
  end

  def create
      if @current_user && @current_user.admin
    country = Country.create country_params

    redirect_to country
     end
  end

  def edit
    if @current_user && @current_user.admin
    @country = Country.find params[:id]
    end
  end

  def update
    if @current_user && @current_user.admin
    country = Country.find params[:id]
    country.update country_params

    redirect_to country
    end
  end

  def destroy
    if @current_user && @current_user.admin
    country = Country.find params[:id]
    country.destroy

    redirect_to countries_path
    end
  end

  private

  def country_params
    params.require(:country).permit(:name, :location_id, :capitalCity, :currency, :population, :area, :popDensity, :flag, :capitalLatitude, :capitalLongitude, :language)
  end


end

# t.text    "name"
# t.integer "location_id"
# t.text    "capitalCity"
# t.text    "currency"
# t.text    "population"
# t.text    "area"
# t.text    "popDensity"
# t.text    "flag"
# t.text    "visa"
# t.text    "capitalLatitude"
# t.text    "capitalLongitude"
# t.text    "language"

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<!--
t.text    "name"
t.integer "location_id"
t.text    "capitalCity"
t.text    "currency"
t.text    "population"
t.text    "area"
t.text    "popDensity"
t.text    "flag"
t.text    "visa"
t.text    "capitalLatitude"
t.text    "capitalLongitude"
t.text    "language" -->

<%= form_for @country do |f| %>

<div class='col-md-6 col-md-offset-3'>
  <div class="stepsDetailsShow specialForm">

  <p>
    <%= f.label :name, :class => "labels", :class => "label1" %>
    <%= f.text_field :name, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :location_id, :class => "labels", :class => "label1" %>
      <% sorted_locations = Location.all.sort_by { |l| l.name } %>
    <%= f.select :location_id, sorted_locations.map { |a| [ a.name, a.id ]}, :include_blank => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :capitalCity, :class => "labels", :class => "label1" %>
    <%= f.text_field :capitalCity, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :currency, :class => "labels", :class => "label1" %>
    <%= f.text_field :currency, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :population, :class => "labels", :class => "label1" %>
    <%= f.text_field :population, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :area, :class => "labels", :class => "label1" %>
    <%= f.text_field :area, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :popDensity, :class => "labels", :class => "label1" %>
    <%= f.text_field :popDensity, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :flag, :class => "labels", :class => "label1" %>
    <%= f.url_field :flag, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :capitalLatitude, :class => "labels", :class => "label1" %>
    <%= f.text_field :capitalLatitude, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :capitalLongitude, :class => "labels", :class => "label1" %>
    <%= f.text_field :capitalLongitude, :required => true, :class => "inputs", :class => "label2" %>
  </p>

  <p>
    <%= f.label :language, :class => "labels", :class => "label1" %>
    <%= f.text_field :language, :required => true, :class => "inputs", :class => "label2" %>
  </p>

<br>

  <%= f.submit %>

</div>
</div>

<% end %>

app/views/countries/edit.html.erb
<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
        <h2>Edit <%= @country.name %></h2>
      </div>
  </div>
  <br>

<% if @current_user %>
    <%= render :partial => 'form' %>
<% end %>

</div>

app/views/countries/index.html.erb
<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
              <h2>This should show all the countries:</h2>
            </div>
    </div>

    <% if @current_user && @current_user.admin %>

        <br>

          <div class='row text-center'>
                  <div class='col-md-12'>
                        <button type='button' class='btn btn-lg btn-default'><%= link_to "Create a new country", new_country_path %></button>
                  </div>
          </div>

      <br>
    <% end %>



  <% sorted_locations = @locations.sort {|l1, l2| l1.name <=> l2.name } %>
  <% sorted_locations.each do |location| %>

      <% sorted_countries = location.countries.sort {|c1, c2| c1.name <=> c2.name } %>
      <% sorted_countries.each do |country| %>

            <div class='col-md-4'>
                <div class="stepsDetailsShow">

                  <h4><%= link_to country.name, "/countries/#{country.id}" %></h4>

                  <%= link_to(image_tag( country.flag, :class => 'thumbnail'), country) %>

                  <h5>Location: <span><%= link_to country.location.name, "/locations/#{country.location.id}" %></span></h5>
                  <h5>Capital city: <span><%= country.capitalCity %></span></h5>
                  <h5>Language: <span><%= country.language %></span></h5>
                  <h5>Currency: <span><%= country.currency %></span></h5>
                  <h5>Population: <span><%= country.population %></span></h5>
                  <h5>Area: <span><%= country.area %></span></h5>
                  <h5>Population density: <span><%= country.popDensity %></span></h5>
                </div>
        </div>
      <% end %>
    <% end %>

</div>

<!--
t.text :name
t.integer :location_id
t.text :capitalCity
t.text :currency
t.text :population
t.text :area
t.text :popDensity
t.text :flag
t.text :visa
t.text :capitalLatitude
t.text :capitalLongitude -->

app/views/countries/new.html.erb
<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
        <h2>Create a new country:</h2>
      </div>
  </div>

  <br>

<% if @current_user %>
      <%= render :partial => 'form' %>
<% end %>

</div>

app/views/countries/show.html.erb
<br>
<div class='container'>
  <div class='row text-center'>
          <div class='col-md-12'>
            <h2><%= @country.name %></h2>
          </div>
  </div>

  <br>

<div class='row'>
        <div class='col-md-12'>
              <div id="map"></div>
        </div>
</div>

<br>
<div class='row'>
    <div class='col-md-8'>
            <div class="stepsDetailsShow">
                  <%= link_to(image_tag( @country.flag, :class => 'featured'), @country) %>
            </div>
    </div>

    <div class='col-md-4'>
      <div class="stepsDetailsShow">
              <h5>Location: <span><%= link_to @country.location.name, "/locations/#{@country.location.id}" %></span></h5>
              <h5>Capital city: <span><%= @country.capitalCity %></span></h5>
              <h5>Language: <span><%= @country.language %></span></h5>
              <h5>Currency: <span><%= @country.currency %></span></h5>
              <h5>Population: <span><%= @country.population %></span></h5>
              <h5>Area: <span><%= @country.area %></span></h5>
              <h5>Population density: <span><%= @country.popDensity %></span></h5>

                <br>

<% if @current_user && @current_user.admin %>
              <div class='row text-center'>
              <button type='button' class='btn btn btn-default'><%= link_to "Edit Country", edit_country_path( @country ), :class => "links" %></button>

              <button type='button' class='btn btn btn-default'><%= link_to "Delete Country", @country, :method => :delete, :data => { :confirm => 'Are you sure?'}, :class => "links" %></button>
              </div>
<% end %>

        </div>
      </div>
    </div>

      <div class='row text-center'>
              <div class='col-md-12'>
                      <h3>Visits:</h3>
              </div>
      </div>

      <br>

<% sorted_visits = @country.visits.sort {|v1, v2| v1.name <=> v2.name } %>
<% sorted_visits.each do |visit| %>

    <div class='col-md-4'>
      <div class="stepsDetails">
              <!-- <h4><%= visit.name %>:</h4>
              <%= link_to( image_tag(visit.image, :class => 'thumbnail'), visit ) %> -->

              <h4><%= link_to visit.name, "/visits/#{visit.id}" %></h4>

              <%= link_to(image_tag( visit.image, :class => 'thumbnail'), visit) %>
              <h5>Location: <span><%= link_to visit.country.location.name, "/locations/#{visit.country.location.id}" %></span></h5>
              <h5>Country: <span><%= link_to visit.country.name, "/countries/#{visit.country.id}" %></span></h5>
              <h5>Description: <span><%= truncate( visit.description, :length => 300)%></span></h5>

      </div>
    </div>

          <% end %>

</div>



<script>
    function initMap() {

      var mapDiv = document.getElementById('map');
      var map = new google.maps.Map(mapDiv, {
        center: {lat: <%= @country.capitalLatitude %>, lng: <%= @country.capitalLongitude %>},
        zoom: 4
      });

      var iconBase = 'http://maps.google.com/mapfiles/kml/paddle/A.png';

      var marker = new google.maps.Marker({
        position: {lat: <%= @country.capitalLatitude %>, lng: <%= @country.capitalLongitude %>},
        map: map,
        icon: iconBase
      });
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
      async defer></script>


      <!-- t.text :name
      t.integer :location_id
      t.text :capitalCity
      t.text :currency
      t.text :population
      t.text :area
      t.text :popDensity
      t.text :flag
      t.text :visa
      t.text :capitalLatitude
      t.text :capitalLongitude -->