config/routes.rb
Rails.application.routes.draw do


  resources :users, :trips, :locations, :countries, :visits, :steps

  get "/login" => 'session#new', :as => 'login'
  post "/login" => 'session#create'
  delete "/logout" => 'session#destroy', :as => 'logout'

end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id               :integer          not null, primary key
#  name             :text
#  location_id      :integer
#  capitalCity      :text
#  currency         :text
#  population       :text
#  area             :text
#  popDensity       :text
#  flag             :text
#  visa             :text
#  capitalLatitude  :text
#  capitalLongitude :text
#  language         :text
#

class Country < ActiveRecord::Base
  belongs_to :location
  has_many :visits
  has_many :steps, :through => :visits
end

app/models/location.rb
# project2cedric $ rails generate model Location --skip

# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  name       :text
#  population :text
#  area       :text
#

class Location < ActiveRecord::Base
  has_many :countries
  has_many :visits, :through => :countries
end

app/models/step.rb
# == Schema Information
#
# Table name: steps
#
#  id         :integer          not null, primary key
#  name       :text
#  trip_id    :integer
#  visit_id   :integer
#  duration   :text
#  position   :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Step < ActiveRecord::Base
  belongs_to :trip
  belongs_to :visit
end

app/models/theme.rb
# == Schema Information
#
# Table name: themes
#
#  id          :integer          not null, primary key
#  name        :text
#  description :text
#

class Theme < ActiveRecord::Base
  has_many :visits
  has_many :steps, :through => :visits
end

app/models/trip.rb
# project2cedric $ rails generate model Trip --skip

# == Schema Information
#
# Table name: trips
#
#  id          :integer          not null, primary key
#  name        :text
#  description :text
#  startDate   :date
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :steps
  has_many :visits, :through => :steps
end

app/models/user.rb
# login $ rails generate model User name:text email:text password_digest:text

# add gems:
      # gem 'annotate'
      # gem 'pry-rails'
      # login $ bundle
      # login $ annotate
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :text
#  email           :text
#  password_digest :text
#  admin           :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :trips
  has_many :steps, :through => :trips
end

app/models/visit.rb
# == Schema Information
#
# Table name: visits
#
#  id             :integer          not null, primary key
#  name           :text
#  country_id     :integer
#  theme_id       :integer
#  description    :text
#  image          :text
#  visitLatitude  :text
#  visitLongitude :text
#

class Visit < ActiveRecord::Base
  belongs_to :country
  belongs_to :theme
  has_many :steps
end

app/controllers/session_controller.rb
# login $ rails generate controller Session new

class SessionController < ApplicationController

  before_action :authenticate, :only => [:new]

  def new
  end

  def create
    user = User.find_by :email => params[:email]

    if user.present? && user.authenticate( params[:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in"
      redirect_to user
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Successfully logged out"
    redirect_to login_path
  end

  private
  def authenticate
    redirect_to users_path if @current_user
  end


end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

      def index
        @steps = Step.all

      end

      def show
        @step = Step.find params[:id]
      end

      def new
        @step = Step.new
        @locations = Location.all
      end

      def create
        step = Step.create step_params

        redirect_to step
      end

      def edit
        @step = Step.find params[:id]
        @locations = Location.all
      end

      def update
        step = Step.find params[:id]
        step.update step_params

        redirect_to step
      end

      def destroy
        step = Step.find params[:id]

        step.destroy
        redirect_to "/trips/#{step.trip.id}"

      end

      private

      def step_params

        params.require(:step).permit(:name, :duration, :position, :trip_id, :visit_id)
      end


end

app/controllers/trips_controller.rb
# project2cedric $ rails generate controller Trips index new show edit

class TripsController < ApplicationController

    def index
      @trips = Trip.all
      @users = User.all
    end

    def show
      @trip = Trip.find params[:id]
    end

    def new
      @trip = Trip.new
    end

    def create
      trip = Trip.create trip_params

      redirect_to new_step_path
    end

    def edit
      @trip = Trip.find params[:id]
    end

    def update
      trip = Trip.find params[:id]
      trip.update trip_params

      redirect_to trip
    end

    def destroy
      trip = Trip.find params[:id]
      trip.destroy

      redirect_to trips_path
    end

    private

    def trip_params
      params.require(:trip).permit(:name, :description, :startDate, :user_id, :image)
    end

end

# t.text :name
# t.text :description
# t.date :startDate
# t.integer :user_id

app/controllers/users_controller.rb
# login $ rails generate controller Users index new show edit


class UsersController < ApplicationController


  def index
     @users = User.all
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  def edit
      @user = User.find params[:id]
  end

  def update
      user = User.find params[:id]
      user.update user_params

      redirect_to user

  end


    def destroy
        user = User.find params[:id]
        user.destroy

        redirect_to users_path

    end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
    end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

    def index
      @visits = Visit.all
      @countries = Country.all
      @locations = Location.all

    end

    def show
      @visit = Visit.find params[:id]
    end

    def new
      if @current_user && @current_user.admin
      @visit = Visit.new
      end
    end

    def create
      if @current_user && @current_user.admin
      visit = Visit.create visit_params

      redirect_to visit
      end
    end

    def edit
      if @current_user && @current_user.admin
      @visit = Visit.find params[:id]
      end
    end

    def update
      if @current_user && @current_user.admin
      visit = Visit.find params[:id]
      visit.update visit_params

      redirect_to visit
      end
    end

    def destroy
      if @current_user && @current_user.admin
      visit = Visit.find params[:id]
      visit.destroy

      redirect_to visits_path
      end
    end

    private

    def visit_params
      params.require(:visit).permit(:name, :country_id, :theme_id, :description, :image, :visitLatitude, :visitLongitude)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>

<!--

"show all the users" = /users
"view a profile" = /users/1
"edit a user" = /users/1/edit
"delete an account" = /users/1/delete
"create an account" = /users/new

 -->


  <div class='navbar navbar-default navbar-static-top'>
      <div class='container'>

        <a href="/login" class='navbar-brand'>Create amazing trips</a>

        <ul class='nav navbar-nav navbar-right'>
            <% if @current_user && @current_user.admin %>
                <li><%= link_to "All users", users_path %></li>
            <% end %>

            <% if @current_user %>

                <li><a href="#" data-toggle='dropdown'><%=@current_user.name%>'s trips<span class='caret'></span></a>
                    <ul class='dropdown-menu'>
                         <li><%= link_to( "See your trips", trips_path( @user)) %></li>
                         <li><%= link_to "Create a new trip", new_trip_path(@current_user) %></li>
                    </ul>
                </li>

                <li><a href="#" data-toggle='dropdown'>All the visits<span class='caret'></span></a>
                    <ul class='dropdown-menu'>

                        <li><%= link_to "See all the locations", locations_path, :class => "links" %></li>
                        <li><%= link_to "See all the countries", countries_path, :class => "links" %></li>
                        <li class='divider'></li>
                        <li><%= link_to "See all the visits", visits_path, :class => "links" %></li>

                    </ul>
                </li>

                <li><a href="#" data-toggle='dropdown'><%=@current_user.name%>'s account<span class='caret'></span></a>
                    <ul class='dropdown-menu'>
                          <li><%= link_to "View profile", @current_user %></li>
                          <li><%= link_to "Edit profile", edit_user_path(@current_user) %></li>
                          <li class='divider'></li>
                          <li><%= link_to "Delete account", user_path(@current_user), :method => :delete, :data => { :confirm => 'Are you sure?'} %></li>
                          <li class='divider'></li>
                          <li><%= link_to "Logout", logout_path, :method => :delete %></li>
                    </ul>
                </li>



            <% else %>
                <li><%= link_to "Sign in", login_path %></li>
                <li><%= link_to "Sign up", new_user_path %></li>
            <% end %>

        </ul>
    </div>
 </div>

<!--

  <% if @current_user %>
    <p>Your email is <%= @current_user.email %></p>
    <p>Your admin status is <%= @current_user.admin %></p>
  <% end %> -->

  <% if flash[:success] %>
    <p><%= flash[:success] %></p>
  <% end %>

  <% if flash[:error] %>
    <p><%= flash[:error] %></p>
  <% end %>

  <%= yield %>

  <br>
  <br>


  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>